version: "3.7"

services: 
  postgres:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=typeorm
      - POSTGRES_USER=nerd
      - POSTGRES_PASSWORD=nerdiscool
    ports: 
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    image: botjose
volumes:
  pg_data: